config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resource :welcome
  get("/", to: "welcome#root") 

  get("/contact_us", to: "welcome#contact_us") 

  post("/process_contact", to: "welcome#process_contact")

  resource :session, only: [:new, :create, :destroy]

  resources :products do
      resources :reviews, only: [:create, :destroy]
    end
  end


# Build a home and about pages
# Build 'home' and 'about' pages for your Amazon application that just display simple text. Build 'nav bar' to link to both pages. Include a link to the 'contact us' page in the 'nav bar'.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_many(:reviews, dependent: :destroy)

    validates(:title, presence: true, uniqueness: {case_sensitive: false})
        validates(
            :description,
            presence: { message: "must exist" },
            length: { minimum: 5 }
        )
        validates(
            :price,
            numericality: { greater_than_or_equal_to: 0, allow_blank: true }
        )
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  

    validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord

    has_many :products
    has_many :reviews

    has_secure_password

    # validates :last_name :email :password_digest, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    # returns current user if there is a current user
    def current_user
      if session[:user_id].present?
        @current_user ||= User.find session[:user_id] # ||= will only assign @current_user if it is nil. Otherwise continue using it's
      end
    end
    helper_method :current_user
    #helper_method is a rails method that makes controller methods available as helpers on views
    # checks if current_user is nil or not
    def user_signed_in?
      current_user.present?
    end
    helper_method :user_signed_in?
    def authenticate_user!
        unless user_signed_in?
            flash[:danger] = "you need to sign in first"
            redirect_to new_session_path
        end
    end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


    def index
        @products = Product.all.order('updated_at DESC')
        
    
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(params.require(:product).permit(:title, :description, :price))
   
        if @product.save
          redirect_to product_path(@product)
        else
          render :new
        end
    end
    
    def show
      @product = Product.find(params[:id])
      @review = Review.new
      @reviews = @product.reviews.order(created_at: :desc)
    end


    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      # redirect_to product_path(@product)
      render :new
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(params.require(:product).permit(:title, :description, :price))
        redirect_to product_path(@product)
        
      else
        render :edit
      end
    end
    
    



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def create
        @product = Product.find(params[:product_id])
        @review = Review.new review_params
        @review.product = @product
        if @review.save
            redirect_to product_path(@product)
            
        else
            @products = Product.all.order('updated_at DESC')
            render 'products/show'
        end
    end

    def destroy
        @review = Review.find params [:id]
        @review.destroy
        redirect_to product_path(@review.product)
    end

    private

    def review_params
        params.require(:review).permit(:body)
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery  with: :exception
  # skip_before_filter :verify_authenticity_token, if: -> { controller_name == 'sessions' && action_name == 'create' }

  def new
  
  end

  def create
    user = User.find_by_email params[:email]
    if user&.authenticate params[:password]
      session[:user_id] = user.id 
        flash[:success] = "User Logged In"
        redirect_to products_path
    else
      flash[:warning] = "Couldn't Log In"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to products_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    # public methods of a controller are called "actions".
    # These methods are responsible for generatinga response to a request
  
  
    def root
    
    end
  
    def contact_us
        
    end
    def process_contact
        render :thank_you
    end
  
    
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmazonApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<% if @product.errors.present? %>
  <p>
    <%= @product.errors.full_messages.join(', ')%>
  </p>
<% end %>

<%# by default rails forms will submit using XHR/AJAX we'll learn this in the future but for now we want to submit using HTML5 forms so we'll have to set the `local` option to true%>
<%# https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with %>
<%= form_with url:"/products", model: @product, local:true do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field(:title, class: 'form-control')%>
  </div>
  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area(:description, class: 'form-control', cols: 1, rows: 1)%>
  </div>
  <div class='form-group'>
    <%= f.label :price %>
    <%= f.text_field(:price, class: 'form-control', cols: 1, rows: 1)%>
  </div>
  <%= f.submit "Create", class: 'btn btn-primary' %>
<% end %>

app/views/products/edit.html.erb
<h1>
  Edit Question Page
</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}
</style>
</head>
<body>

<div class="topnav">
  <a href="/">Home</a>
  <a href="/contact_us">Contact</a>
  <a class="active" href="/products">Products</a>
</div>

<h1>PRODUCTS</h1>
  <a class="active" href="/products/new">ADD A NEW PRODUCT</a>
</div>

<div class='row'>
  <div class='col-2'>
  </div>

  <div class='col-10'>
    <% @products.each do |product| %>
    <%# if you pass a instance to link_to it will create the href='/questions/:id' %>
    <a href="/products/<%= product.id %>">
        <h4> <%= product.id %> | <%= product.title %> </h4>
       <h4> $ <%= product.price %></h4>
    </a>
    <% end %>

    <%# link_to just creates a `a tag` with the correct href. the below is equivalent to the above code %>
    <% if false %>
      <% @products.each do |product| %>
        <a href="/products/<%= product.id %>">
          <li class='list-group-item'>
            <p><%= product.id %> <%= product.title%> $ <%= product.price%></p>
          </li>
        </a>
      <% end %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>
  New Product Page
</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<div class='shadow-sm p-3 mb-5 bg-white rounded overflow-wrap'>
  <h1>
    <span class='badge badge-pill badge-info'>
      <%= @product.id %>
    </span>
    <%= @product.title %>
    </span>
    <%= @product.description %>
    </span>
    <%= @product.price %>
  </h1>
  <p class='shadow-none p-3 mb-5 bg-light rounded'><%= @product.title %></p>
  <h1>$<%= @product.price %></h1>

  <%# link_to arguments: name, path, options_object %>
  <div>
    <%= link_to(
      "Edit",
      edit_product_path(@product),
      class: 'btn btn-info'
    )
    %>
    <%= link_to(
      "Delete",
      product_path(@product),
      method: :delete,
      class: 'btn btn-danger',
      data: { confirm: 'are you sure?' }
    )
    %>
  </div>


  <%= form_with(model: [@product, @review], local: true) do |f| %>
    <% if @review.errors.present? %>
      <p>
        <%= @review.errors.full_messages.join(', ') %>
      </p>
    <% end %>
    <div>
      <%= f.label :rating %>
      <%= f.number_field :rating %>
    </div>
    <div>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </div>
    <%= f.submit %>
  <% end %>


  <%#
    Display all of the reviews for this product
  %>

  <% @reviews.each do |review| %>
     <ul class="list-group">
       <li class="list-group-item">
        <h3> Rating: <% review.rating %> </h3>
        <p> <% review.body %> </p>
        <% link_to 'Delete',
          product_review_path(@product, review),
          class: "btn btn-danger brn-sm",
              method: :delete, 
              data: {
                  confirm: 'Are you sure that you want to delete this review?'
              }
        %>
        </li>
      </ul>
  <% end %>

app/views/welcome/_navbar.html.erb
<div>
  <div class="topnav">
  <a class="active" href="/">Home</a>
  <a href="/contact_us">Contact</a>
  <a href="/products">Products</a>
    <div>
    <% if user_signed_in? %>
      <%= link_to "Logout", session_path, method: :delete, class: 'btn btn-danger' %>
      <%= current_user.first_name %> <%= current_user.last_name %>
    <% else %>
      <%= link_to "Log In", new_session_path, class: 'btn-btn-danger'%>
    <% end %>
  </div>
</div>


</div>

app/views/welcome/contact_us.html.erb
<%= render 'navbar' %>

<div>
  
    <h1>CONTACT US</h1>

    <%= form_tag("/process_contact") do %>
  <div>
    <%= label_tag(:full_name) %> <br>
    <%= text_field_tag(:full_name) %>
  </div>

  <div>
    <%= label_tag(:email) %> <br>
    <%= email_field_tag(:email) %>
  </div>

  <div>
    <%= label_tag(:message) %> <br>
    <%= text_area_tag(:message) %>
  </div>

  <%= submit_tag("process_contact")%>
<% end %>

</div>



</body>

app/views/welcome/root.html.erb
<%= render 'navbar' %>


<div>
  
  <h1>Welcome to</h1>
  <p>Amazon App</p>

</div>



</body>

app/views/welcome/thank_you.html.erb
<h1>Thank You</h1>

<p>
  Thank You, <strong><%= @full_name %></strong>, for getting in touch!
</p>

<p>
  <strong>Your messsage was:</strong>
  <em><%= @message %>
</p>

<p>
  We'll email you at <%= @email %> shortly.
</p>